import type { Metadata } from 'next'
import {
  Barlow,
  Geist,
  Geist_Mono,
  Macondo,
  Space_Grotesk,
} from 'next/font/google'
import './globals.css'
import Nav from '@/components/nav'
import { ViewTransitions } from 'next-view-transitions'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const macondo = Macondo({
  variable: '--font-geist-macondo',
  subsets: ['latin'],
  weight: ['400'],
})

const barlow = Barlow({
  variable: '--font-barlow',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const grotesk = Space_Grotesk({
  variable: '--font-space-grotesk',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ViewTransitions>
      <html lang='en'>
        <body
          className={`${geistSans.variable} ${grotesk.variable} ${macondo.variable}   ${barlow.variable} ${geistMono.variable} antialiased`}
        >
          <Nav />
          {children}
        </body>
      </html>
    </ViewTransitions>
  )
}
